language: java
jdk:
- oraclejdk8
services:
- postgresql
before_install:
- psql -c 'create database torshare;' -U postgres
- cd service
- cd ..
- "./deploy.sh"
addons:
  postgresql: '9.3'
  apt:
    packages:
    - sshpass
env:
  global:
  - secure: I4Xd03p46wgUX2Mzfpeqk4XdFhHcxfnx2PWm0GO13AGiWgvv8fEBYkTuhoQX2mBbB1xGObs500euvgHVqsACvtpioWP020RK+P1o9TyiNbV6ySrnl6IRDUPomxG6R1jMz6rZHpRSk+9PYgTJ/JhXlEDKZBYAu4eZ1v6aRMO9LC+jFY4127v0lnTOVl2Yda+UdMqx75iDZ/aLS4A6U7haJ6o3mH9XuhhBV/niMoA+C0tlmBa+P82eHGFfpYky2Sxls5vgmyJ2f2CgMrXOOkNiKQN+VnE20HQ/nER1Tu9lnbi8ft8v2Oww310hvcRC8L8Y0jQoS2Z5BX7MTa4Ih3eZDGcJMsKxXHu88wpxH32jveMXvXRgu4ke+f4OOUP/WXJRLUfEvdrqPM4haL23FcZ/th3FoY3s3A8t8lvqW6aBRLyi7umLF2YXqN1IumsU6ofgaU5OQ80iyKGe2hdNvqi+8zSymM1yL190mX3DL08fPKCWIJ17H5v34OF8G73X340Lw64hOSTeaQ6RN/74TGz3kYrC4fvgotaI78NT+pAIoL53zxaAQTUbZCgmWTNrgTfzZPDM42vaf520GoZV9ZT3sC7pGUdNGLeGYthWKgjFvZZQTZT594pVVoEMSOl0vK3q1suS7f0OdNCSfS2LC5tpLbnZTHn+cVA2WW37kIxuEOE=
  - secure: ECKbL9bGn/laDX7uls8/6FlSxDpgm4qR8jTjxuEVNMrok1+FeCvJLYTsfQVD1syn+AHmIH8Mku0Ocqd4nIrnT/uu39l4X5WWFPhEbJHdW98X3u41rnqRok38mF2Lxq0yu86jroMzgNFVab55jWT5m3jj63T/wUm/MUtiALAsZ0wGS4zTfSwDITK6nP7hnFG5XWzOmyPxMT9OdA6ohdTG5ssIlOM4qTgvhfOWaZHvkCRPjXCnQu4pzfzov+H4oEohAU3W57eWyYA3NWkrd8I+B1R3yS2a39JzwNpLeLTWXhMloRK4E89zZpI4jRI5qI6Si6r7x9nqf8iggoWr0t8DePOSGathyNkce7ZrSv1qbNmSgiJW+Et1aONLNH8raayR0wDADpHBMOjhWxBFqIyb/qAQhviBUqReG9g0j6sCG/mUC3wYz2OjnYi6hDkIGZnvrG1Yxg8b4sYF36XP10NUknmrGvw7s6NuiNISDp6M7gJNknRBWpjxnaQI6Nvc/OrbbjMQqWFwhpjWqLj1piEAX2n316kAF9Jd1paB/eoKAdsLoNitsHdLuYMJTWyzIhnhqHPAThsIhd8E7GJx+Ny4n9HaBbWfzW3PsQU+Hw/AOM8/NGVpIOsY9OKGX5l3tEZlQiBvkcif4QSb+gxISYt6/oN/0y1iuHbdSNUUMQWWCC4=
  - secure: hjL4ScI/mZAbuRsAfhRa7Oi8mgnGYo6EfI5ZTcTQrAmj4m/rAtc34KEqNI3n78SxtZClOWpHXkmsQULXROL0QNYKaWypBaZTl7fcl4RZRfAp4dz738mbB6+iMzBv14lSQPYKv0Y073rHjt02K6oWJYJfDxYI0R2rLv8inMedsP3dBK8Ecf92JFzHOJcvE/sKGpecvvI4EhIZ0Bx9DmUmg2W6uw5EI9eUdyOc8Vi2ze0Z7kOLUw1c3VjjEiWn5dAZN65Pz5MmV2BqO4m8fN1b6YQ/hs7frbNW0mAYgimeGtM5wO6FGjU8NKu+qnsb/n3Sr0Ihk4iG+tPtoGpbLyLmNrXMN113MLyhTWSbCOB4uGWRapaesMrvCL9SZDNC3C5hLJzSs023aK6oV09YZo3XLmNhM06BtEMOQDy+onDub2HcZkR54a5FhOxAHpTPMf4aPPnj5uxyf2TZI5nY8XT1ydbR2l0viRtdwPFrX8sx7W0/DovI4yDNPqjJjQli8qi1/+1S3WkidPHy/nLtr3GOLC/1KfUuKDpkx9/fPaV0e4sOY2k2CPNJMI6BbZvD4jNRdX7I3HR2+N6YxGLLa1KnIwDIT9UyjN3d0PiXniOmFiSd3tR7bgHBc4+IzEqTv2bDDTJYLJa37XiCCSKOq6vptgZbxcqb6GDD7rZ53+saatY=
