language: java
jdk:
- oraclejdk8
services:
- postgresql
before_install:
- psql -c "create user torshare with password 'asdf' superuser" -U postgres
- psql -c "create database torshare with owner torshare" -U postgres
- psql -c "create extension pg_trgm" -U postgres
- cd service
after_success:
- cd ..
- "./deploy.sh"
addons:
  postgresql: '9.3'
  apt:
    packages:
    - sshpass
env:
  global:
  - secure: GlioG15MxrUwsjxtPWWjOxpGSrv25ICW0tOU9uiJLMjUxl9Tqav71oHsq3Mxheye6Pefg/K6foxzu8i6og+bvGcvaIQNWpg8hoIyA102fL9X8fFTIYgqWHV/vwFrCifPasCqeiM07CEIHPGe/6DAI0oCa7JZtQ/zzg2PHIf14MC+nklZK95utrnLOevC8zwxevHLLTVI/Rbvko3em7dnHhYlQ+ieDGyO5TXHYJUJC7vR4NT4L99OEwJIMR9Bnrp2xWpkBQSDMx2ud6gvV6IgreuQ3iA30QqenqoTN25rqcM+N60Z9TDqvV3Ats3Fu3uws7+wazaUxtzvsTwjqIpVfuTMFDIx1Uke8GVGBw5362An5lw1Zbxi1oo93TrYSkkO9xMiMAdcndvCkdrgbgNmXZLhEK4Fcu93cod+Y57ldBqXDvPER83rY523TC/ucz4P4FjyM+eOCXF2RcOtXUrscDEXTSXtRe3WPOsn8bDf8fKBu/tM23Kxc+4u58f49ojn8sGet2FVLqOtJBf9LSL/vxYuuF1j8FCDbMoAk2MdJ1io4xjA7T0Q/lwTOo4xnIMeG3CjKByPgkNiRtNEs1h6yOSbXHTenkwyhFfaXOG0bKgcf9MNat6HBZVlj3cXLvWP29zszdXeSI1IeCyebXYWl2SGbDdTP7vr+xMcwmMuCns=
  - secure: s1bUuJEGKtUR8oJ2rQvJEveHgtbSj6a3cs+vDSU9u2MGE2YS740Tk1S7HEl2876aXW5rWcxBPWtwkigmrkWs2nAJWZGcy3rIGzjk+5PVsuxY9fh65nxNLr2Ekm09DnTw5mqaO5mpRl1ZUyHernV+Uc2dHM8P8jw7ScXj/1GESRmYXBjWJ90/F/ykupZSmyso9ci8Fif7MgoWduvoAwuO65y3mG3IZ3SIB7A36kJvbcahPxr24Vu/gGFvT7HRXWPnZDCWttwLLOA43UW4lb05yKRqoECTg5/We63WNeiF/95yKOT/zlrhCVjx5ED9cfhzq/tPg3K2kwuFCU4HwDRVDzXXJmBAk+46hw4HdeqU2T3JMDMQ8tzaera84rkiF9USeHQVH2BEJBDvsp3joOtC81OQiygLacCFqi/k8Xk6UNr6zQIWdipQ4ob1FXqja0HeDnjDW2aUF17WbergPHRDv+B1qWHxLSQjYwGs7TPUeeP7FrCEVwrM45XqN+o3M7DSNiU+V+nuF3ttPfn9xvsIHDdn9xfe+U9MpjfhK0BbJd5bIgYu6XJM9zJQJuCW6XXjfhdq8Llo0T+JmpKFIVEyLdWwGNy3wYuROWpFOFKMuzZw7Xc/gQoNcMNWt8OgZ40YmK/fCutaPluAkWKBGBqQputdBmvpsDurzxwH5kDpdkY=
  - secure: BYCP/PSGLcDMnzSGEiW/d0iOdY87jy3k9YwG+e5OXvo5PMW29FHmiSDJsjowLBoOMy7iZbxoWqrC3svjKqSpi4RyfBnSlTJ0K+iRAuRs4sobWG3JT3x2SVmAXymOWeDDMltPL6XOo4qoQCCXCJ1iieeHi/N1mFiBUxbHyE2s+ArQX42ZR5OFxEzIlsZgTdBRsbBpQpFGuvvAdMzcc2jROJmu4A1r3wq25eJoO22sVdHn81nSilVuHGg8pAREPg/aloQ2Z5ewx1pa+5XrattfOEyGuPs/YYucmNYn/+7tYOkwsDaIYiTU6jH3UFCYG83Qa6haHd5LId0/aADKa5cJG4s0SyxbeCEAOUwKY8MeltgrikCnhXYWaAsTcguwzadB3+ALXicBWfBjZKH1aa/ZZxaOcA4B9qr7FGi81x+Zj4w+ikP/LKM+bVIVPY2d9m8MwxgbyIRu8GTjAVdoD7oRyafvWXqV1g5ZrYVvNA758NJ39grWtqFS+ve+xElMMK3LMdJEIUZZgdvFIsDZK7FgqbLkrKC7NAmH2RIIk+V7lpneuXSQkkBhaI+Tpy24XfpUXZfKuGGPoZXZ290klXNhFdZjHR+w5tDrULOEqLg1Lc6GReOKDOS05I05DiitTtmtInIE7Wnv3RgRhImFfjvT1WxnX2FcA9LE4RjkYRrDTvA=
